---
- name: Give user ssh access
  hosts: all
  become: true
  vars:
    users:
      - someone
      - person

  tasks:
  - name: Add users
    user:
      name: "{{ item }}"
      shell: /bin/bash
      state: present
    with_items: "{{ users }}"
 
  - name: Add users keys
    authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', './keys/' + item + '.pub') }}"
    with_items: "{{ users }}"
